services:
  app:
    build: .
    container_name: reto_ia_container
    ports:
      - "8000:8000"   # API de Python
      - "8081:8081"   # Servidor Metro de Expo (React Native)
      - "19000:19000" # Puerto alternativo de Expo si fuera necesario
    volumes:
      - .:/app
    environment:
      - WATCHPACK_POLLING=true
    stdin_open: true
    tty: true