services:
  # --- EL MOTOR (PYTHON + FASTAPI) ---
  backend:
    build: .
    container_name: reto_ia_backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - WATCHPACK_POLLING=true
      - OLLAMA_BASE_URL=http://ollama:11434
      - OLLAMA_MODEL=qwen2.5:7b-instruct
      - OLLAMA_KEEP_ALIVE=1h
      - OLLAMA_TEMPERATURE=0.2
      - PYTHONUNBUFFERED=1
      - TTS_SPEED=1.2
      - TTS_VOLUME_DB=0.0
      
    command: uvicorn src.app:app --host 0.0.0.0 --port 8000 --reload --timeout-keep-alive 30
    depends_on:
      - ollama


      # --- LLM LOCAL (OLLAMA) ---
  ollama:
    image: ollama/ollama:latest
    container_name: reto_ia_ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    # Comenta si NO tienes GPU NVIDIA y el toolkit instalado en el host:
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped

  # --- LA APP MÓVIL (REACT NATIVE + EXPO) ---
  #
  #frontend:
  #  build: .
  #  container_name: reto_ia_frontend
  #  ports:
  #    - "8081:8081"
  #    - "19000:19000"
  #  volumes:
  #    - .:/app
  #  environment:
  #    - WATCHPACK_POLLING=true
  #  # Entra directo a la carpeta y arranca el túnel automáticamente
  #  command: sh -c "cd src/frontend && npx expo start --tunnel"
  #  stdin_open: true # Mantiene el contenedor atento a tus comandos de teclado
  #  tty: true        # Permite ver los colores y el código QR bien dibujado

volumes:
  ollama_data: